$ANSIBLE_VAULT;1.1;AES256
64653039363239623539343533323865343235396661326563336664613932663433366335356162
6435363837613639666461666232363065623935643233650a383064313739313130363533336336
36316561663635366230303333343934623130363133626162613961393363346435346634376534
6530303065393137350a633839383562373537303838373865333035386230396165626633626337
38383834626337623138373633353137376333303634663938633235653239343832383234333264
3834663839306336666535373730366661643533633030373862
