---
- name: Connectivity test + basic facts
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping device (network_cli)
      ansible.netcommon.cli_command:
        command: "/system/routerboard/print"
      register: out

    - name: Print output
      ansible.builtin.debug:
        var: out.stdout
